#!/bin/bash


if ! lsmod | grep hpcap >> $logfile 2>&1 ; then
	install_hpcap # Ensure everything is installed correctly
fi

begin_test "Traffic RX"

recv_iface="hpcap${receiver_port}"

ensure_link $recv_iface

base_losses=$(get_iface_losses $recv_iface)
base_rx=$(get_iface_rx $recv_iface)
receiver_core=$(get_core_for_receiver $receiver_port)

trap on_exit EXIT

log "Starting hpcapdd in core $receiver_core with port $receiver_port"

taskset -c $receiver_core bin/release/hpcapdd $receiver_port 0 null >> $logfile 2>&1 &
hpcapdd_pid="$!"

if ! is_pid_running $hpcapdd_pid &> /dev/null ; then
	log "hpcapdd did not start correctly"
	test_fail_die # I should get all this if into a function, but for now it works.
fi

log "hpcapdd running"

# Settings for the generator (rate, framesize) are loaded from the config file
start_generator $generation_rate_Mbps $generation_frame_size

log "Waiting for test to complete..."

sleep $generation_duration_seconds

log "Woke up, stopping."

kill -TERM $hpcapdd_pid >> $logfile 2>&1
stop_generator

final_losses=$(get_iface_losses $recv_iface)
final_rx=$(get_iface_rx $recv_iface)

log "Final losses: $final_losses (there were $base_losses before the test)"
log "Final rx bytes: $final_rx (there were $base_rx before the test)"

if [ $final_losses -lt $((base_losses + loss_margin)) ] && [ $final_rx -gt $base_rx ]; then
	test_ok
else
	test_fail
fi
